# Hey, thanks for using my theme. If you like this theme,checkout my repo (https://gitlab.com/avron/gruvhugo"
# and drop a star while you're at it. ;)
baseurl = "https://papunmohanty.github.io/"
title = "Papun Mohanty"
languageCode = "en-us"
paginate = "10" # Number of posts per page
#disqusShortname = "" # Enable comments by entering your Disqus shortname
#googleAnalytics = "" # Enable Google Analytics by entering your tracking id
#-------------------------------------------------------------------------------
# DEFAULT SETTINGS
#-------------------------------------------------------------------------------

# Default Theme
theme= "gruvhugo"

# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex = true
  metaKeywords = "fast, hugo, theme, minimal, gruvbox"
  headerTitle = "Papun Mohanty"
  copyright = "Â© 2022 Papun Mohanty.  <a href=\"https://creativecommons.org/licenses/by/4.0/\">Some rights reserved</a>."
  name = "papunmohanty"
  img = "img/papunmohanty.jpg"
  img_title = "Thanks to Christina @ wocintechchat.com for this photo."
  icon = "img/logo.png"
  quote = "Kind, focused, concerned, compassion towards people and tech"
  description= "Experience in Designing, Developing, Containerizing and Hosting Cloud Native Applications using Python, Django, Flask, FastAPI, NodeJS, PySpark, Dask on AWS and GCP cloud platforms empowered with Docker, Kubernetes and Helm. Experience in creating ETL Pipelines using Apache Airflow for various SQL and NoSQL based Databases."
  licenseUrl = ""

# Social icons
  [[params.social]]
    name = "gitlab"
    url  = "https://github.com/papunmohanty"

  [[params.social]]
    name = "email"
    url  = "mailto:mail@mail.com"

  [[params.social]]
    name = "gpg"
    url  = "https://keys.openpgp.org/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/papunmohanty"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

[params.style]
  # add path to custom CSS files here
  custom_css = ["css/style.css"]
  # add path to custom SCSS files here
  custom_scss = []

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"

  [[menu.main]]
    identifier = "post"
    name       = "Posts"
    url        = "post/"

  [[menu.main]]
    identifier = "wiki"
    name       = "Wiki"
    url        = "none"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    docType = "article"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = true
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
